training_config: configs/training/enformer_split_hic_only.yaml
checkpoint: data/trained_models/enformer_split/hicfoundation_enformer_best.ckpt
output_dir: outputs/enformer_split_inference/hic_only
group: both
batch_size: 128
num_workers: 4
